### ISSUE TITLE
Some questions of how to run the suite 

### ISSUE THREAD

**Issue by robinren03** [sarahgrace/mirovia#38]
When running driver.py, it gives out the following instructions:
> Device: 0
> Problem size: 1
> *****
> /home/xxx/mirovia/src/cuda/level0/busspeeddownload/busspeeddownload
> Traceback (most recent call last):
> File "driver.py", line 66, in <module>
>  run_benchmark(options, b)
> File "driver.py", line 29, in run_benchmark
>    p = subprocess.Popen([path, '-s', str(options.size), '-o', result_path, '-d', str(options.device), '-q'])
>  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>    errread, errwrite)
>  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>    raise child_exception
> OSError: [Errno 2] No such file or directory

Meanwhile , when I run src/level1/bfs/makefile, it gives out the following instructions:
> depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> g++ -DHAVE_CONFIG_H -I. -I../../../../config  -I -I../../../../src/cuda/common -Wformat  -I../../../../src/common -I../../../../config  -g -O2 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o ./../../common/main.cpp &&\
> mv -f $depbase.Tpo $depbase.Po
./../../common/main.cpp:5:19: fatal error: cuda.h: No such file or directory
> compilation terminated.
> Makefile:386: recipe for target 'main.o' failed
> make: *** [main.o] Error 1

How can I solve them?

**Comment by rossbach** [comment]
Hello-
Mirovia has been superseded by Altis and is no longer being maintained. Please see: https://github.com/utcs-scea/altis
Thanks,
Chris
